"""Tasks deadline not null

Revision ID: 0825ae2d0144
Revises: bbb01f56b386
Create Date: 2026-04-02 23:03:13.529169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0825ae2d0144"
down_revision: Union[str, None] = "bbb01f56b386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "deadline", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "deadline", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###
